type ServerEnvKey =
  | "NEXT_PUBLIC_APP_URL"
  | "NEXT_PUBLIC_SUPABASE_URL"
  | "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  | "SUPABASE_SERVICE_ROLE_KEY"
  | "STRIPE_SECRET_KEY"
  | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
  | "STRIPE_WEBHOOK_SECRET"
  | "STRIPE_STARTER_PRICE_ID"
  | "STRIPE_GROWTH_PRICE_ID"
  | "STRIPE_PRO_PRICE_ID";

function ensureEnv(key: ServerEnvKey) {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Missing required environment variable: ${key}`);
  }
  return value;
}

export const env = {
  NEXT_PUBLIC_APP_URL: ensureEnv("NEXT_PUBLIC_APP_URL"),
  NEXT_PUBLIC_SUPABASE_URL: ensureEnv("NEXT_PUBLIC_SUPABASE_URL"),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ensureEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
  SUPABASE_SERVICE_ROLE_KEY: ensureEnv("SUPABASE_SERVICE_ROLE_KEY"),
  STRIPE_SECRET_KEY: ensureEnv("STRIPE_SECRET_KEY"),
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ensureEnv(
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
  ),
  STRIPE_WEBHOOK_SECRET: ensureEnv("STRIPE_WEBHOOK_SECRET"),
  STRIPE_STARTER_PRICE_ID: ensureEnv("STRIPE_STARTER_PRICE_ID"),
  STRIPE_GROWTH_PRICE_ID: ensureEnv("STRIPE_GROWTH_PRICE_ID"),
  STRIPE_PRO_PRICE_ID: ensureEnv("STRIPE_PRO_PRICE_ID"),
};
